//List of action types/"scenarios" when calling the Article API

export const NEW_ARTICLE = "NEW_ARTICLE"
export const NEW_ARTICLE_FAILED = "NEW_ARTICLE_FAILED"
export const GET_ARTICLE = "GET_ARTICLE"
export const GET_ARTICLE_FAILED = "GET_ARTICLE_FAILED"
export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES"
export const GET_ALL_ARTICLES_FAILED = "GET_ALL_ARTICLES_FAILED"
export const UPDATE_ARTICLE = "UPDATE_ARTICLE"
export const UPDATE_ARTICLE_FAILED = "UPDATED_ARTICLE_FAILED"
export const DELETE_ARTICLE = "DELETE_ARTICLE"
export const DELETE_ARTICLE_FAILED = "DELETE_ARTICLE_FAILED"
export const GET_ALL_ARTICLES_BY_WRITER = "GET_ALL_WRITERS_FOR_WRITER"
export const GET_ALL_ARTICLES_BY_WRITER_FAILED = "GET_ALL_WRITERS_FOR_WRITER_FAILED"
