//List of action types/"scenarios" when calling the Comment API

export const NEW_COMMENT = "NEW_COMMENT"
export const NEW_COMMENT_FAILED = "NEW_COMMENT_FAILED"
export const GET_COMMENT = "GET_COMMENT"
export const GET_COMMENT_FAILED = "GET_COMMENT_FAILED"
export const UPDATE_COMMENT = "UPDATE_COMMENT"
export const UPDATE_COMMENT_FAILED = "UPDATED_COMMENT_FAILED"
export const DELETE_COMMENT = "DELETE_COMMENT"
export const DELETE_COMMENT_FAILED = "DELETE_COMMENT_FAILED"
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS"
export const GET_ALL_COMMENTS_FAILED = "GET_ALL_COMMENTS_FAILED"
export const GET_COMMENTS_FOR_ARTICLE = "GET_COMMENTS_FOR_ARTICLE"
export const GET_COMMENTS_FOR_ARTICLE_FAILED = "GET_COMMENTS_FOR_ARTICLE_FAILED"
