//List of action types/"scenarios" when calling the Editor API

export const NEW_EDITOR = "NEW_EDITOR"
export const NEW_EDITOR_FAILED = "NEW_EDITOR_FAILED"
export const GET_EDITOR = "GET_EDITOR"
export const GET_EDITOR_FAILED = "GET_EDITOR_FAILED"
export const GET_ALL_EDITORS = "GET_ALL_EDITORS"
export const GET_ALL_EDITORS_FAILED = "GET_ALL_EDITORS_FAILED"
export const UPDATE_EDITOR = "UPDATE_EDITOR"
export const UPDATE_EDITOR_FAILED = "UPDATED_EDITOR_FAILED"
export const DELETE_EDITOR = "DELETE_EDITOR"
export const DELETE_EDITOR_FAILED = "DELETE_EDITOR_FAILED"
export const GET_EDITOR_BY_USER ="GET_EDITOR_BY_USER"
export const GET_EDITOR_BY_USER_FAILED = "GET_EDITOR_BY_USER_FAILED"
